ShowSpot/ShowSpot/Controllers/ConteudosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ShowSpot.Data;
using ShowSpot.Models;

namespace ShowSpot.Controllers
{
    public class ConteudosController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public ConteudosController(ILogger<HomeController> logger, ApplicationDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        
        public IActionResult VistaFilmes()
        {
            var result = _context.Conteudos
                .Where(c => c.Tipo == false)
                .OrderByDescending(c => c.Id)
                .Take(50)
                .Select(c => new
                {
                    c.Id,
                    c.Nome,
                    c.ImgUrl,
                    c.Sinopse,
                    c.Rating,
                    c.Tipo,
                    c.Runtime,
                    c.AnoLancamento,
                    c.LinkTrailer,
                    Tag = _context.ConteudoTags
                        .Where(ct => ct.ConteudoFK == c.Id)
                        .Join(_context.Tags, ct => ct.TagFK, t => t.Id, (ct, t) => t.Nome)
                        .FirstOrDefault()
                });

            var tags = _context.Tags.Select(t => t.Nome);

            ViewBag.Filmes = JsonConvert.SerializeObject(result);
            ViewBag.Tags = JsonConvert.SerializeObject(tags);

            return View();
        }

        public IActionResult VistaSeries()
        {
            var result = _context.Conteudos
                .Where(c => c.Tipo == true)
                .OrderByDescending(c => c.Id)
                .Take(50)
                .Select(c => new
                {
                    c.Id,
                    c.Nome,
                    c.ImgUrl,
                    c.Sinopse,
                    c.Rating,
                    c.Tipo,
                    c.Runtime,
                    c.AnoLancamento,
                    c.LinkTrailer,
                    Tag = _context.ConteudoTags
                        .Where(ct => ct.ConteudoFK == c.Id)
                        .Join(_context.Tags, ct => ct.TagFK, t => t.Id, (ct, t) => t.Nome)
                        .FirstOrDefault()
                });

            var tags = _context.Tags.Select(t => t.Nome);
            
            ViewBag.Series = JsonConvert.SerializeObject(result);
            ViewBag.Tags = JsonConvert.SerializeObject(tags);
            
            return View();
        }

        public IActionResult ViewBiblioteca()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Name);

            var user = _context.Users.Where(e => e.UserName == userEmail).FirstOrDefault();

            if (user == null)
            {
                return new JsonResult(NotFound());
            }

            var userFavs = _context.Favoritos
                .Where(f => f.UserFK == user.Id.ToString())
                .Join(_context.Conteudos, fav => fav.ConteudosFK, c => c.Id, (fav, c) => new
                {
                    c.Id,
                    c.Nome,
                    c.ImgUrl,
                    c.Sinopse,
                    c.Rating,
                    c.Tipo,
                    c.Runtime,
                    c.AnoLancamento,
                    c.LinkTrailer,
                    Tag = _context.ConteudoTags
                        .Where(ct => ct.ConteudoFK == c.Id)
                        .Join(_context.Tags, ct => ct.TagFK, t => t.Id, (ct, t) => t.Nome)
                        .FirstOrDefault()
                })
                .OrderByDescending(c => c.Id)
                .Take(50)
                .ToList();

            ViewBag.Favoritos = JsonConvert.SerializeObject(userFavs);
            
            var userWL = _context.WatchLaters
                .Where(f => f.UtilizadorFK == user.Id.ToString())
                .Join(_context.Conteudos, fav => fav.ConteudosFK, c => c.Id, (fav, c) => new
                {
                    c.Id,
                    c.Nome,
                    c.ImgUrl,
                    c.Sinopse,
                    c.Rating,
                    c.Tipo,
                    c.Runtime,
                    c.AnoLancamento,
                    c.LinkTrailer,
                    Tag = _context.ConteudoTags
                        .Where(ct => ct.ConteudoFK == c.Id)
                        .Join(_context.Tags, ct => ct.TagFK, t => t.Id, (ct, t) => t.Nome)
                        .FirstOrDefault()
                })
                .OrderByDescending(c => c.Id)
                .Take(50)
                .ToList();
            
            ViewBag.WatchLaters = JsonConvert.SerializeObject(userWL);

            return View();
        }

        // GET: Conteudos
        public async Task<IActionResult> Index()
        {
            var user = User.FindFirstValue(ClaimTypes.Name);
            if(user != null) user = user.Split('@')[0];
            if(user == "admin") return _context.Conteudos != null ? 
                View(await _context.Conteudos.ToListAsync()) :
                Problem("Entity set 'ApplicationDbContext.Conteudos'  is null.");
            return Forbid();
              
        }

        // GET: Conteudos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Conteudos == null)
            {
                return NotFound();
            }

            var conteudos = await _context.Conteudos
                .Select(c => new
                {
                    c.Id,
                    c.Nome,
                    c.ImgUrl,
                    c.Sinopse,
                    c.Rating,
                    c.Tipo,
                    c.Runtime,
                    c.AnoLancamento,
                    c.LinkTrailer,
                    Tag = _context.ConteudoTags
                        .Where(ct => ct.ConteudoFK == c.Id)
                        .Join(_context.Tags, ct => ct.TagFK, t => t.Id, (ct, t) => t.Nome)
                        .FirstOrDefault()
                }).FirstOrDefaultAsync(m => m.Id == id);
            if (conteudos == null)
            {
                return NotFound();
            }

            ViewBag.Conteudo = JsonConvert.SerializeObject(conteudos);

            return View();
        }

        // GET: Conteudos/Create
        public IActionResult Create()
        {
            var user = User.FindFirstValue(ClaimTypes.Name);
            if(user != null) user = user.Split('@')[0];
            if(user == "admin") return View(); 
            return Forbid();
        }

        // POST: Conteudos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,ImgUrl,Sinopse,Rating,Tipo,Runtime")] Conteudos conteudos)
        {
            string runtimeRegex = "";
            string errorMessage = "";

            if (conteudos.Tipo)
            {
                // x episodes, y seasons
                runtimeRegex = @"^\d+ episódios, \d+ temporadas$";
                errorMessage = "Runtime deve de ser 'x episódios, y temporadas'";
            }
            else
            {
                runtimeRegex = @"^[1-4]h[0-5]?\d$";
                errorMessage = "Runtime deve de ser algo como xhy, com x entre 1 e 4, e y entre 0 e 59";
            }

            if (string.IsNullOrEmpty(conteudos.Runtime) || !Regex.IsMatch(conteudos.Runtime, runtimeRegex))
            {
                ModelState.AddModelError("Runtime", errorMessage);
            }

            if (ModelState.IsValid)
            {
                _context.Add(conteudos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(conteudos);
        }

        // GET: Conteudos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Conteudos == null)
            {
                return NotFound();
            }

            var conteudos = await _context.Conteudos.FindAsync(id);
            if (conteudos == null)
            {
                return NotFound();
            }
            
            var user = User.FindFirstValue(ClaimTypes.Name);
if(user != null) user = user.Split('@')[0];
            if(user == "admin") return View(conteudos); 
            return Forbid();
        }

        // POST: Conteudos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,ImgUrl,Sinopse,Rating,Tipo,Runtime")] Conteudos conteudos)
        {
            if (id != conteudos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conteudos);
                    await _context.SaveChangesAsync();
                }

ShowSpot/ShowSpot/Views/Conteudos/Create.cshtml
@model ShowSpot.Models.Conteudos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Conteudos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sinopse" class="control-label"></label>
                <input asp-for="Sinopse" class="form-control" />
                <span asp-validation-for="Sinopse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Tipo" /> @Html.DisplayNameFor(model => model.Tipo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkTrailer" class="control-label"></label>
                <input asp-for="LinkTrailer" class="form-control" />
                <span asp-validation-for="LinkTrailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShowSpot/ShowSpot/Views/Conteudos/Delete.cshtml
@model ShowSpot.Models.Conteudos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Conteudos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImgUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImgUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sinopse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sinopse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkTrailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkTrailer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShowSpot/ShowSpot/Views/Conteudos/Details.cshtml
@using Newtonsoft.Json
@using System.Security.Claims
@model ShowSpot.Models.Conteudos

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/css/style.css" />
<div>
    <div class='row contentCard'>
                    <div class='col-4 contentCard-left d-flex flex-column'>
                        <img class="mt-4 mb-2" style="objectFit: 'contain' ; height: 450px" src="@JsonConvert.DeserializeObject(ViewBag.Conteudo).ImgUrl"/>
                        <div class="row justify-content-center text-center mb-5"><strong>@JsonConvert.DeserializeObject(ViewBag.Conteudo).Nome</strong></div>
                        <div class="row fs-6 justify-content-center">Ano lançamento: @JsonConvert.DeserializeObject(ViewBag.Conteudo).AnoLancamento</div>
                        <div class="row fs-6 justify-content-center">Duração: @JsonConvert.DeserializeObject(ViewBag.Conteudo).Runtime</div>
                        <div class="row fs-6 justify-content-center">Rating: @JsonConvert.DeserializeObject(ViewBag.Conteudo).Rating</div>

                        @if(User.FindFirstValue(ClaimTypes.Name) != null){
                            <div clas = "row fs-6 justify-content-center " style="text-align: center">
                                <a type="submit" class="btn btn-secondary" asp-controller="Conteudos" asp-action="addFavorito" asp-route-idC="@JsonConvert.DeserializeObject(ViewBag.Conteudo).Id">Adicionar à biblioteca</a>
                            </div>
                            <div clas = "row fs-6 justify-content-center text-center"  style="text-align: center">
                                <a type="submit" class="btn btn-secondary" asp-controller="Conteudos" asp-action="addWatchLater" asp-route-idC="@JsonConvert.DeserializeObject(ViewBag.Conteudo).Id">Ver mais tarde</a>
                            </div>
                        }
                    </div>
                    <div class='col contentCard-right'>
                        <div class="row m-2 mb-3">Sinopse:</div>
                        <div class="row fs-4 ps-5 pe-5 justify-content-center mb-5">@JsonConvert.DeserializeObject(ViewBag.Conteudo).Sinopse</div>
                        <div class="row justify-content-center mb-5">
                        <iframe height="500" src="@JsonConvert.DeserializeObject(ViewBag.Conteudo).LinkTrailer" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
</div>

ShowSpot/ShowSpot/Views/Conteudos/Edit.cshtml
@model ShowSpot.Models.Conteudos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Conteudos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sinopse" class="control-label"></label>
                <input asp-for="Sinopse" class="form-control" />
                <span asp-validation-for="Sinopse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Tipo" /> @Html.DisplayNameFor(model => model.Tipo)
                </label>
            </div>
            
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label"></label>
                <input asp-for="AnoLancamento" class="form-control" />
                <span asp-validation-for="AnoLancamento" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                    <label asp-for="LinkTrailer" class="control-label"></label>
                    <input asp-for="LinkTrailer" class="form-control" />
                    <span asp-validation-for="LinkTrailer" class="text-danger"></span>
                </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShowSpot/ShowSpot/Views/Conteudos/Filmes.cshtml
@page
@model ShowSpot.Views.Conteudos.FilmesModel
@{
}

ShowSpot/ShowSpot/Views/Conteudos/Index.cshtml
@model IEnumerable<ShowSpot.Models.Conteudos>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sinopse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Runtime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImgUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sinopse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Runtime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ShowSpot/ShowSpot/Views/Conteudos/ViewBiblioteca.cshtml
@using Newtonsoft.Json
@model dynamic

@{
    ViewBag.Title = "Biblioteca";
}

<link rel="stylesheet" href="~/css/style.css" />
<div class="mt-3 pt-2 pb-3 text-center">
    <h1 class="loginRegisterFont">Favoritos</h1>
    <div class="all_filmes d-flex justify-content-center">
        @foreach (var conteudo in JsonConvert.DeserializeObject(@ViewBag.Favoritos))
        {
            <a class="filmeHref" href='/conteudos/details/@conteudo.Id'>
                <div class="filmeCard">
                    <img class="filmes" alt="filme" src='@conteudo.ImgUrl' title='@conteudo.Nome'/>
                    <div class="filme-overlay">
                        <strong>@conteudo.Nome</strong>
                        <span class="position-absolute bottom-0 fs-5 mb-2" style="left: 0px ; right: 0px">@conteudo.Rating</span>
                    </div>
                </div>
            </a>
        }
    </div>
    
    <h1 class="loginRegisterFont">Watch Later</h1>
    <div class="all_filmes d-flex justify-content-center">
        @foreach (var conteudo in JsonConvert.DeserializeObject(@ViewBag.WatchLaters))
        {
            <a class="filmeHref" href='/conteudos/details/@conteudo.Id'>
                <div class="filmeCard">
                    <img class="filmes" alt="filme" src='@conteudo.ImgUrl' title='@conteudo.Nome'/>
                    <div class="filme-overlay">
                        <strong>@conteudo.Nome</strong>
                        <span class="position-absolute bottom-0 fs-5 mb-2" style="left: 0px ; right: 0px">@conteudo.Rating</span>
                    </div>
                </div>
            </a>
        }
    </div>
</div>

ShowSpot/ShowSpot/Views/Conteudos/VistaFilmes.cshtml
@using Newtonsoft.Json
@model IEnumerable<ShowSpot.Models.Conteudos>
@{
    ViewData["Title"] = "Filmes";
}

<div class ="text-center">
    <link rel="stylesheet" href="~/css/style.css" />
    <div class="container-fluid p-0" style= "overflow:hidden">
        <div class="row" style= "maxHeight: 100%">
            <div class="mt-3 pt-2 pb-3">
                @foreach (var tag in JsonConvert.DeserializeObject(@ViewBag.Tags))
                {
                    <div class="mt-3 pt-2 pb-3">
                        <h1 class="loginRegisterFont">@tag</h1>
                        <div class="all_filmes d-flex justify-content-center">
                            @foreach (var conteudo in JsonConvert.DeserializeObject(@ViewBag.Filmes))
                            {
                                @if (@conteudo.Tag == @tag)
                                {
                                    <a class="filmeHref" href='/conteudos/details/@conteudo.Id'>
                                        <div class="filmeCard">
                                            <img class="filmes" alt="filme" src='@conteudo.ImgUrl' title='@conteudo.Nome'/>
                                            <div class="filme-overlay">
                                                <strong>@conteudo.Nome</strong>
                                                <span class="position-absolute bottom-0 fs-5 mb-2" style="left: 0px ; right: 0px">@conteudo.Rating</span>
                                            </div>
                                        </div>
                                    </a>
                                }
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ShowSpot/ShowSpot/Views/Conteudos/VistaSeries.cshtml
@using Newtonsoft.Json
@model IEnumerable<ShowSpot.Models.Conteudos>
@{
    ViewData["Title"] = "Filmes";
}

<div class="text-center">
    <link rel="stylesheet" href="~/css/style.css" />
    <div class="container-fluid p-0" style="overflow:hidden ">
        <div class="row" style="maxHeight: 100%">
            <div class="mt-3 pt-2 pb-3">
                @foreach (var tag in JsonConvert.DeserializeObject(@ViewBag.Tags))
                                {
                                    <div class="mt-3 pt-2 pb-3">
                                        <h1 class="loginRegisterFont">@tag</h1>
                                        <div class="all_filmes d-flex justify-content-center">
                                            @foreach (var conteudo in JsonConvert.DeserializeObject(@ViewBag.Series))
                                            {
                                                @if (@conteudo.Tag == @tag)
                                                {
                                                    <a class="filmeHref" href='/conteudos/details/@conteudo.Id'>
                                                        <div class="filmeCard">
                                                            <img class="filmes" alt="filme" src='@conteudo.ImgUrl' title='@conteudo.Nome'/>
                                                            <div class="filme-overlay">
                                                                <strong>@conteudo.Nome</strong>
                                                                <span class="position-absolute bottom-0 fs-5 mb-2" style="left: 0px ; right: 0px">@conteudo.Rating</span>
                                                            </div>
                                                        </div>
                                                    </a>
                                                }
                                            }
                                        </div>
                                    </div>
                                }
            </div>
        </div>
    </div>
</div>